// go run mksyscall_solaris_sparc64.go -tags solaris,all,all syscall_solaris.go
// Code generated by the command above; see README.md. DO NOT EDIT.

//go:build solaris && amd64 && gc
// +build solaris,amd64,gc

package unix

import (
	"unsafe"
)

//go:cgo_import_dynamic libc_pipe pipe "libc.so"
//go:cgo_import_dynamic libc_pipe2 pipe2 "libc.so"
//go:cgo_import_dynamic libsocket_getsockname getsockname "libsocket.so"
//go:cgo_import_dynamic libc_getcwd getcwd "libc.so"
//go:cgo_import_dynamic libc_getgroups getgroups "libc.so"
//go:cgo_import_dynamic libc_setgroups setgroups "libc.so"
//go:cgo_import_dynamic libc_wait4 wait4 "libc.so"
//go:cgo_import_dynamic libc_gethostname gethostname "libc.so"
//go:cgo_import_dynamic libc_utimes utimes "libc.so"
//go:cgo_import_dynamic libc_utimensat utimensat "libc.so"
//go:cgo_import_dynamic libc_fcntl fcntl "libc.so"
//go:cgo_import_dynamic libc_futimesat futimesat "libc.so"
//go:cgo_import_dynamic libsocket_accept accept "libsocket.so"
//go:cgo_import_dynamic libsocket___xnet_recvmsg __xnet_recvmsg "libsocket.so"
//go:cgo_import_dynamic libsocket___xnet_sendmsg __xnet_sendmsg "libsocket.so"
//go:cgo_import_dynamic libc_acct acct "libc.so"
//go:cgo_import_dynamic libc___makedev __makedev "libc.so"
//go:cgo_import_dynamic libc___major __major "libc.so"
//go:cgo_import_dynamic libc___minor __minor "libc.so"
//go:cgo_import_dynamic libc_ioctl ioctl "libc.so"
//go:cgo_import_dynamic libc_ioctl ioctl "libc.so"
//go:cgo_import_dynamic libc_poll poll "libc.so"
//go:cgo_import_dynamic libc_access access "libc.so"
//go:cgo_import_dynamic libc_adjtime adjtime "libc.so"
//go:cgo_import_dynamic libc_chdir chdir "libc.so"
//go:cgo_import_dynamic libc_chmod chmod "libc.so"
//go:cgo_import_dynamic libc_chown chown "libc.so"
//go:cgo_import_dynamic libc_chroot chroot "libc.so"
//go:cgo_import_dynamic libc_clock_gettime clock_gettime "libc.so"
//go:cgo_import_dynamic libc_close close "libc.so"
//go:cgo_import_dynamic libc_creat creat "libc.so"
//go:cgo_import_dynamic libc_dup dup "libc.so"
//go:cgo_import_dynamic libc_dup2 dup2 "libc.so"
//go:cgo_import_dynamic libc_exit exit "libc.so"
//go:cgo_import_dynamic libc_faccessat faccessat "libc.so"
//go:cgo_import_dynamic libc_fchdir fchdir "libc.so"
//go:cgo_import_dynamic libc_fchmod fchmod "libc.so"
//go:cgo_import_dynamic libc_fchmodat fchmodat "libc.so"
//go:cgo_import_dynamic libc_fchown fchown "libc.so"
//go:cgo_import_dynamic libc_fchownat fchownat "libc.so"
//go:cgo_import_dynamic libc_fdatasync fdatasync "libc.so"
//go:cgo_import_dynamic libc_flock flock "libc.so"
//go:cgo_import_dynamic libc_fpathconf fpathconf "libc.so"
//go:cgo_import_dynamic libc_fstat fstat "libc.so"
//go:cgo_import_dynamic libc_fstatat fstatat "libc.so"
//go:cgo_import_dynamic libc_fstatvfs fstatvfs "libc.so"
//go:cgo_import_dynamic libc_getdents getdents "libc.so"
//go:cgo_import_dynamic libc_getgid getgid "libc.so"
//go:cgo_import_dynamic libc_getpid getpid "libc.so"
//go:cgo_import_dynamic libc_getpgid getpgid "libc.so"
//go:cgo_import_dynamic libc_getpgrp getpgrp "libc.so"
//go:cgo_import_dynamic libc_geteuid geteuid "libc.so"
//go:cgo_import_dynamic libc_getegid getegid "libc.so"
//go:cgo_import_dynamic libc_getppid getppid "libc.so"
//go:cgo_import_dynamic libc_getpriority getpriority "libc.so"
//go:cgo_import_dynamic libc_getrlimit getrlimit "libc.so"
//go:cgo_import_dynamic libc_getrusage getrusage "libc.so"
//go:cgo_import_dynamic libc_getsid getsid "libc.so"
//go:cgo_import_dynamic libc_gettimeofday gettimeofday "libc.so"
//go:cgo_import_dynamic libc_getuid getuid "libc.so"
//go:cgo_import_dynamic libc_kill kill "libc.so"
//go:cgo_import_dynamic libc_lchown lchown "libc.so"
//go:cgo_import_dynamic libc_link link "libc.so"
//go:cgo_import_dynamic libsocket___xnet_llisten __xnet_llisten "libsocket.so"
//go:cgo_import_dynamic libc_lstat lstat "libc.so"
//go:cgo_import_dynamic libc_madvise madvise "libc.so"
//go:cgo_import_dynamic libc_mkdir mkdir "libc.so"
//go:cgo_import_dynamic libc_mkdirat mkdirat "libc.so"
//go:cgo_import_dynamic libc_mkfifo mkfifo "libc.so"
//go:cgo_import_dynamic libc_mkfifoat mkfifoat "libc.so"
//go:cgo_import_dynamic libc_mknod mknod "libc.so"
//go:cgo_import_dynamic libc_mknodat mknodat "libc.so"
//go:cgo_import_dynamic libc_mlock mlock "libc.so"
//go:cgo_import_dynamic libc_mlockall mlockall "libc.so"
//go:cgo_import_dynamic libc_mprotect mprotect "libc.so"
//go:cgo_import_dynamic libc_msync msync "libc.so"
//go:cgo_import_dynamic libc_munlock munlock "libc.so"
//go:cgo_import_dynamic libc_munlockall munlockall "libc.so"
//go:cgo_import_dynamic libc_nanosleep nanosleep "libc.so"
//go:cgo_import_dynamic libc_open open "libc.so"
//go:cgo_import_dynamic libc_openat openat "libc.so"
//go:cgo_import_dynamic libc_pathconf pathconf "libc.so"
//go:cgo_import_dynamic libc_pause pause "libc.so"
//go:cgo_import_dynamic libc_pread pread "libc.so"
//go:cgo_import_dynamic libc_pwrite pwrite "libc.so"
//go:cgo_import_dynamic libc_read read "libc.so"
//go:cgo_import_dynamic libc_readlink readlink "libc.so"
//go:cgo_import_dynamic libc_rename rename "libc.so"
//go:cgo_import_dynamic libc_renameat renameat "libc.so"
//go:cgo_import_dynamic libc_rmdir rmdir "libc.so"
//go:cgo_import_dynamic libc_lseek lseek "libc.so"
//go:cgo_import_dynamic libc_select select "libc.so"
//go:cgo_import_dynamic libc_setegid setegid "libc.so"
//go:cgo_import_dynamic libc_seteuid seteuid "libc.so"
//go:cgo_import_dynamic libc_setgid setgid "libc.so"
//go:cgo_import_dynamic libc_sethostname sethostname "libc.so"
//go:cgo_import_dynamic libc_setpgid setpgid "libc.so"
//go:cgo_import_dynamic libc_setpriority setpriority "libc.so"
//go:cgo_import_dynamic libc_setregid setregid "libc.so"
//go:cgo_import_dynamic libc_setreuid setreuid "libc.so"
//go:cgo_import_dynamic libc_setsid setsid "libc.so"
//go:cgo_import_dynamic libc_setuid setuid "libc.so"
//go:cgo_import_dynamic libsocket_shutdown shutdown "libsocket.so"
//go:cgo_import_dynamic libc_stat stat "libc.so"
//go:cgo_import_dynamic libc_statvfs statvfs "libc.so"
//go:cgo_import_dynamic libc_symlink symlink "libc.so"
//go:cgo_import_dynamic libc_sync sync "libc.so"
//go:cgo_import_dynamic libc_sysconf sysconf "libc.so"
//go:cgo_import_dynamic libc_times times "libc.so"
//go:cgo_import_dynamic libc_truncate truncate "libc.so"
//go:cgo_import_dynamic libc_fsync fsync "libc.so"
//go:cgo_import_dynamic libc_ftruncate ftruncate "libc.so"
//go:cgo_import_dynamic libc_umask umask "libc.so"
//go:cgo_import_dynamic libc_uname uname "libc.so"
//go:cgo_import_dynamic libc_umount umount "libc.so"
//go:cgo_import_dynamic libc_unlink unlink "libc.so"
//go:cgo_import_dynamic libc_unlinkat unlinkat "libc.so"
//go:cgo_import_dynamic libc_ustat ustat "libc.so"
//go:cgo_import_dynamic libc_utime utime "libc.so"
//go:cgo_import_dynamic libsocket___xnet_bind __xnet_bind "libsocket.so"
//go:cgo_import_dynamic libsocket___xnet_connect __xnet_connect "libsocket.so"
//go:cgo_import_dynamic libc_mmap mmap "libc.so"
//go:cgo_import_dynamic libc_munmap munmap "libc.so"
//go:cgo_import_dynamic libsendfile_sendfile sendfile "libsendfile.so"
//go:cgo_import_dynamic libsocket___xnet_sendto __xnet_sendto "libsocket.so"
//go:cgo_import_dynamic libsocket___xnet_socket __xnet_socket "libsocket.so"
//go:cgo_import_dynamic libsocket___xnet_socketpair __xnet_socketpair "libsocket.so"
//go:cgo_import_dynamic libc_write write "libc.so"
//go:cgo_import_dynamic libsocket___xnet_getsockopt __xnet_getsockopt "libsocket.so"
//go:cgo_import_dynamic libsocket_getpeername getpeername "libsocket.so"
//go:cgo_import_dynamic libsocket_setsockopt setsockopt "libsocket.so"
//go:cgo_import_dynamic libsocket_recvfrom recvfrom "libsocket.so"
//go:cgo_import_dynamic libc_port_create port_create "libc.so"
//go:cgo_import_dynamic libc_port_associate port_associate "libc.so"
//go:cgo_import_dynamic libc_port_dissociate port_dissociate "libc.so"
//go:cgo_import_dynamic libc_port_get port_get "libc.so"
//go:cgo_import_dynamic libc_port_getn port_getn "libc.so"
//go:cgo_import_dynamic libc_putmsg putmsg "libc.so"
//go:cgo_import_dynamic libc_getmsg getmsg "libc.so"

//go:linkname libc_pipe libc_pipe
//go:linkname libc_pipe2 libc_pipe2
//go:linkname libsocket_getsockname libsocket_getsockname
//go:linkname libc_getcwd libc_getcwd
//go:linkname libc_getgroups libc_getgroups
//go:linkname libc_setgroups libc_setgroups
//go:linkname libc_wait4 libc_wait4
//go:linkname libc_gethostname libc_gethostname
//go:linkname libc_utimes libc_utimes
//go:linkname libc_utimensat libc_utimensat
//go:linkname libc_fcntl libc_fcntl
//go:linkname libc_futimesat libc_futimesat
//go:linkname libsocket_accept libsocket_accept
//go:linkname libsocket___xnet_recvmsg libsocket___xnet_recvmsg
//go:linkname libsocket___xnet_sendmsg libsocket___xnet_sendmsg
//go:linkname libc_acct libc_acct
//go:linkname libc___makedev libc___makedev
//go:linkname libc___major libc___major
//go:linkname libc___minor libc___minor
//go:linkname libc_ioctl libc_ioctl
//go:linkname libc_ioctl libc_ioctl
//go:linkname libc_poll libc_poll
//go:linkname libc_access libc_access
//go:linkname libc_adjtime libc_adjtime
//go:linkname libc_chdir libc_chdir
//go:linkname libc_chmod libc_chmod
//go:linkname libc_chown libc_chown
//go:linkname libc_chroot libc_chroot
//go:linkname libc_clock_gettime libc_clock_gettime
//go:linkname libc_close libc_close
//go:linkname libc_creat libc_creat
//go:linkname libc_dup libc_dup
//go:linkname libc_dup2 libc_dup2
//go:linkname libc_exit libc_exit
//go:linkname libc_faccessat libc_faccessat
//go:linkname libc_fchdir libc_fchdir
//go:linkname libc_fchmod libc_fchmod
//go:linkname libc_fchmodat libc_fchmodat
//go:linkname libc_fchown libc_fchown
//go:linkname libc_fchownat libc_fchownat
//go:linkname libc_fdatasync libc_fdatasync
//go:linkname libc_flock libc_flock
//go:linkname libc_fpathconf libc_fpathconf
//go:linkname libc_fstat libc_fstat
//go:linkname libc_fstatat libc_fstatat
//go:linkname libc_fstatvfs libc_fstatvfs
//go:linkname libc_getdents libc_getdents
//go:linkname libc_getgid libc_getgid
//go:linkname libc_getpid libc_getpid
//go:linkname libc_getpgid libc_getpgid
//go:linkname libc_getpgrp libc_getpgrp
//go:linkname libc_geteuid libc_geteuid
//go:linkname libc_getegid libc_getegid
//go:linkname libc_getppid libc_getppid
//go:linkname libc_getpriority libc_getpriority
//go:linkname libc_getrlimit libc_getrlimit
//go:linkname libc_getrusage libc_getrusage
//go:linkname libc_getsid libc_getsid
//go:linkname libc_gettimeofday libc_gettimeofday
//go:linkname libc_getuid libc_getuid
//go:linkname libc_kill libc_kill
//go:linkname libc_lchown libc_lchown
//go:linkname libc_link libc_link
//go:linkname libsocket___xnet_llisten libsocket___xnet_llisten
//go:linkname libc_lstat libc_lstat
//go:linkname libc_madvise libc_madvise
//go:linkname libc_mkdir libc_mkdir
//go:linkname libc_mkdirat libc_mkdirat
//go:linkname libc_mkfifo libc_mkfifo
//go:linkname libc_mkfifoat libc_mkfifoat
//go:linkname libc_mknod libc_mknod
//go:linkname libc_mknodat libc_mknodat
//go:linkname libc_mlock libc_mlock
//go:linkname libc_mlockall libc_mlockall
//go:linkname libc_mprotect libc_mprotect
//go:linkname libc_msync libc_msync
//go:linkname libc_munlock libc_munlock
//go:linkname libc_munlockall libc_munlockall
//go:linkname libc_nanosleep libc_nanosleep
//go:linkname libc_open libc_open
//go:linkname libc_openat libc_openat
//go:linkname libc_pathconf libc_pathconf
//go:linkname libc_pause libc_pause
//go:linkname libc_pread libc_pread
//go:linkname libc_pwrite libc_pwrite
//go:linkname libc_read libc_read
//go:linkname libc_readlink libc_readlink
//go:linkname libc_rename libc_rename
//go:linkname libc_renameat libc_renameat
//go:linkname libc_rmdir libc_rmdir
//go:linkname libc_lseek libc_lseek
//go:linkname libc_select libc_select
//go:linkname libc_setegid libc_setegid
//go:linkname libc_seteuid libc_seteuid
//go:linkname libc_setgid libc_setgid
//go:linkname libc_sethostname libc_sethostname
//go:linkname libc_setpgid libc_setpgid
//go:linkname libc_setpriority libc_setpriority
//go:linkname libc_setregid libc_setregid
//go:linkname libc_setreuid libc_setreuid
//go:linkname libc_setsid libc_setsid
//go:linkname libc_setuid libc_setuid
//go:linkname libsocket_shutdown libsocket_shutdown
//go:linkname libc_stat libc_stat
//go:linkname libc_statvfs libc_statvfs
//go:linkname libc_symlink libc_symlink
//go:linkname libc_sync libc_sync
//go:linkname libc_sysconf libc_sysconf
//go:linkname libc_times libc_times
//go:linkname libc_truncate libc_truncate
//go:linkname libc_fsync libc_fsync
//go:linkname libc_ftruncate libc_ftruncate
//go:linkname libc_umask libc_umask
//go:linkname libc_uname libc_uname
//go:linkname libc_umount libc_umount
//go:linkname libc_unlink libc_unlink
//go:linkname libc_unlinkat libc_unlinkat
//go:linkname libc_ustat libc_ustat
//go:linkname libc_utime libc_utime
//go:linkname libsocket___xnet_bind libsocket___xnet_bind
//go:linkname libsocket___xnet_connect libsocket___xnet_connect
//go:linkname libc_mmap libc_mmap
//go:linkname libc_munmap libc_munmap
//go:linkname libsendfile_sendfile libsendfile_sendfile
//go:linkname libsocket___xnet_sendto libsocket___xnet_sendto
//go:linkname libsocket___xnet_socket libsocket___xnet_socket
//go:linkname libsocket___xnet_socketpair libsocket___xnet_socketpair
//go:linkname libc_write libc_write
//go:linkname libsocket___xnet_getsockopt libsocket___xnet_getsockopt
//go:linkname libsocket_getpeername libsocket_getpeername
//go:linkname libsocket_setsockopt libsocket_setsockopt
//go:linkname libsocket_recvfrom libsocket_recvfrom
//go:linkname libc_port_create libc_port_create
//go:linkname libc_port_associate libc_port_associate
//go:linkname libc_port_dissociate libc_port_dissociate
//go:linkname libc_port_get libc_port_get
//go:linkname libc_port_getn libc_port_getn
//go:linkname libc_putmsg libc_putmsg
//go:linkname libc_getmsg libc_getmsg

type syscallFunc uintptr

var (
	libc_pipe,
	libc_pipe2,
	libsocket_getsockname,
	libc_getcwd,
	libc_getgroups,
	libc_setgroups,
	libc_wait4,
	libc_gethostname,
	libc_utimes,
	libc_utimensat,
	libc_fcntl,
	libc_futimesat,
	libsocket_accept,
	libsocket___xnet_recvmsg,
	libsocket___xnet_sendmsg,
	libc_acct,
	libc___makedev,
	libc___major,
	libc___minor,
	libc_ioctl,
	libc_ioctl,
	libc_poll,
	libc_access,
	libc_adjtime,
	libc_chdir,
	libc_chmod,
	libc_chown,
	libc_chroot,
	libc_clock_gettime,
	libc_close,
	libc_creat,
	libc_dup,
	libc_dup2,
	libc_exit,
	libc_faccessat,
	libc_fchdir,
	libc_fchmod,
	libc_fchmodat,
	libc_fchown,
	libc_fchownat,
	libc_fdatasync,
	libc_flock,
	libc_fpathconf,
	libc_fstat,
	libc_fstatat,
	libc_fstatvfs,
	libc_getdents,
	libc_getgid,
	libc_getpid,
	libc_getpgid,
	libc_getpgrp,
	libc_geteuid,
	libc_getegid,
	libc_getppid,
	libc_getpriority,
	libc_getrlimit,
	libc_getrusage,
	libc_getsid,
	libc_gettimeofday,
	libc_getuid,
	libc_kill,
	libc_lchown,
	libc_link,
	libsocket___xnet_llisten,
	libc_lstat,
	libc_madvise,
	libc_mkdir,
	libc_mkdirat,
	libc_mkfifo,
	libc_mkfifoat,
	libc_mknod,
	libc_mknodat,
	libc_mlock,
	libc_mlockall,
	libc_mprotect,
	libc_msync,
	libc_munlock,
	libc_munlockall,
	libc_nanosleep,
	libc_open,
	libc_openat,
	libc_pathconf,
	libc_pause,
	libc_pread,
	libc_pwrite,
	libc_read,
	libc_readlink,
	libc_rename,
	libc_renameat,
	libc_rmdir,
	libc_lseek,
	libc_select,
	libc_setegid,
	libc_seteuid,
	libc_setgid,
	libc_sethostname,
	libc_setpgid,
	libc_setpriority,
	libc_setregid,
	libc_setreuid,
	libc_setsid,
	libc_setuid,
	libsocket_shutdown,
	libc_stat,
	libc_statvfs,
	libc_symlink,
	libc_sync,
	libc_sysconf,
	libc_times,
	libc_truncate,
	libc_fsync,
	libc_ftruncate,
	libc_umask,
	libc_uname,
	libc_umount,
	libc_unlink,
	libc_unlinkat,
	libc_ustat,
	libc_utime,
	libsocket___xnet_bind,
	libsocket___xnet_connect,
	libc_mmap,
	libc_munmap,
	libsendfile_sendfile,
	libsocket___xnet_sendto,
	libsocket___xnet_socket,
	libsocket___xnet_socketpair,
	libc_write,
	libsocket___xnet_getsockopt,
	libsocket_getpeername,
	libsocket_setsockopt,
	libsocket_recvfrom,
	libc_port_create,
	libc_port_associate,
	libc_port_dissociate,
	libc_port_get,
	libc_port_getn,
	libc_putmsg,
	libc_getmsg syscallFunc
)

// Implemented in runtime/syscall_solaris.go.
func rawSysvicall6(trap, nargs, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
func sysvicall6(trap, nargs, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpipe(p uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_pipe)), 1, p, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpipe2(p uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_pipe2)), 2, p, uintptr(flags), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetsockname(fd int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket_getsockname)), 3, uintptr(fd), rsa, addrlen, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetcwd(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getcwd)), 2, _p0, uintptr(_lenp0), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetgroups(ngid int, gid uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getgroups)), 2, uintptr(ngid), gid, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetgroups(ngid int, gid uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setgroups)), 2, uintptr(ngid), gid, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callwait4(pid int32, statusp uintptr, options int, rusage uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_wait4)), 4, uintptr(pid), statusp, uintptr(options), rusage, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgethostname(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_gethostname)), 2, _p0, uintptr(_lenp0), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutimes(_p0 uintptr, times uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_utimes)), 2, _p0, times, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutimensat(fd int, _p0 uintptr, times uintptr, flag int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_utimensat)), 4, uintptr(fd), _p0, times, uintptr(flag), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfcntl(fd uintptr, cmd int, arg uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fcntl)), 3, fd, uintptr(cmd), arg, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfutimesat(fildes int, path uintptr, times uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_futimesat)), 3, uintptr(fildes), path, times, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callaccept(s int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket_accept)), 3, uintptr(s), rsa, addrlen, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_recvmsg(s int, msg uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_recvmsg)), 3, uintptr(s), msg, uintptr(flags), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_sendmsg(s int, msg uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_sendmsg)), 3, uintptr(s), msg, uintptr(flags), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callacct(path uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_acct)), 1, path, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__makedev(version int, major int, minor int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc___makedev)), 3, uintptr(version), uintptr(major), uintptr(minor), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__major(version int, dev uint64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc___major)), 2, uintptr(version), uintptr(dev), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__minor(version int, dev uint64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc___minor)), 2, uintptr(version), uintptr(dev), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callioctl(fd int, req int, arg uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_ioctl)), 3, uintptr(fd), uintptr(req), arg, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callioctl(fd int, req int, arg uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_ioctl)), 3, uintptr(fd), uintptr(req), arg, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpoll(fds uintptr, nfds int, timeout int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_poll)), 3, fds, uintptr(nfds), uintptr(timeout), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callaccess(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_access)), 2, _p0, uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calladjtime(delta uintptr, olddelta uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_adjtime)), 2, delta, olddelta, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchdir(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_chdir)), 1, _p0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchmod(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_chmod)), 2, _p0, uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchown(_p0 uintptr, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_chown)), 3, _p0, uintptr(uid), uintptr(gid), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchroot(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_chroot)), 1, _p0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callclock_gettime(clockid int32, time uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_clock_gettime)), 2, uintptr(clockid), time, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callclose(fd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_close)), 1, uintptr(fd), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callcreat(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_creat)), 2, _p0, uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calldup(fd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_dup)), 1, uintptr(fd), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calldup2(oldfd int, newfd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_dup2)), 2, uintptr(oldfd), uintptr(newfd), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callexit(code int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_exit)), 1, uintptr(code), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfaccessat(dirfd int, _p0 uintptr, mode uint32, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_faccessat)), 4, uintptr(dirfd), _p0, uintptr(mode), uintptr(flags), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchdir(fd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fchdir)), 1, uintptr(fd), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchmod(fd int, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fchmod)), 2, uintptr(fd), uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchmodat(dirfd int, _p0 uintptr, mode uint32, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fchmodat)), 4, uintptr(dirfd), _p0, uintptr(mode), uintptr(flags), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchown(fd int, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fchown)), 3, uintptr(fd), uintptr(uid), uintptr(gid), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchownat(dirfd int, _p0 uintptr, uid int, gid int, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fchownat)), 5, uintptr(dirfd), _p0, uintptr(uid), uintptr(gid), uintptr(flags), 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfdatasync(fd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fdatasync)), 1, uintptr(fd), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callflock(fd int, how int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_flock)), 2, uintptr(fd), uintptr(how), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfpathconf(fd int, name int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fpathconf)), 2, uintptr(fd), uintptr(name), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstat(fd int, stat uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fstat)), 2, uintptr(fd), stat, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstatat(fd int, _p0 uintptr, stat uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fstatat)), 4, uintptr(fd), _p0, stat, uintptr(flags), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstatvfs(fd int, vfsstat uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fstatvfs)), 2, uintptr(fd), vfsstat, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetdents(fd int, _p0 uintptr, _lenp0 int, basep uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getdents)), 4, uintptr(fd), _p0, uintptr(_lenp0), basep, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetgid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getgid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getpid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpgid(pid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getpgid)), 1, uintptr(pid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpgrp() (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getpgrp)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgeteuid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_geteuid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetegid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getegid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetppid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getppid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpriority(which int, who int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getpriority)), 2, uintptr(which), uintptr(who), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetrlimit(which int, lim uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getrlimit)), 2, uintptr(which), lim, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetrusage(who int, rusage uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getrusage)), 2, uintptr(who), rusage, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetsid(pid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getsid)), 1, uintptr(pid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgettimeofday(tv uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_gettimeofday)), 1, tv, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetuid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_getuid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callkill(pid int, signum int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_kill)), 2, uintptr(pid), uintptr(signum), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllchown(_p0 uintptr, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_lchown)), 3, _p0, uintptr(uid), uintptr(gid), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllink(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_link)), 2, _p0, _p1, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_llisten(s int, backlog int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_llisten)), 2, uintptr(s), uintptr(backlog), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllstat(_p0 uintptr, stat uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_lstat)), 2, _p0, stat, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmadvise(_p0 uintptr, _lenp0 int, advice int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_madvise)), 3, _p0, uintptr(_lenp0), uintptr(advice), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkdir(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mkdir)), 2, _p0, uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkdirat(dirfd int, _p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mkdirat)), 3, uintptr(dirfd), _p0, uintptr(mode), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkfifo(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mkfifo)), 2, _p0, uintptr(mode), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkfifoat(dirfd int, _p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mkfifoat)), 3, uintptr(dirfd), _p0, uintptr(mode), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmknod(_p0 uintptr, mode uint32, dev int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mknod)), 3, _p0, uintptr(mode), uintptr(dev), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmknodat(dirfd int, _p0 uintptr, mode uint32, dev int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mknodat)), 4, uintptr(dirfd), _p0, uintptr(mode), uintptr(dev), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmlock(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mlock)), 2, _p0, uintptr(_lenp0), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmlockall(flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mlockall)), 1, uintptr(flags), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmprotect(_p0 uintptr, _lenp0 int, prot int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mprotect)), 3, _p0, uintptr(_lenp0), uintptr(prot), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmsync(_p0 uintptr, _lenp0 int, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_msync)), 3, _p0, uintptr(_lenp0), uintptr(flags), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunlock(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_munlock)), 2, _p0, uintptr(_lenp0), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunlockall() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_munlockall)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callnanosleep(time uintptr, leftover uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_nanosleep)), 2, time, leftover, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callopen(_p0 uintptr, mode int, perm uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_open)), 3, _p0, uintptr(mode), uintptr(perm), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callopenat(dirfd int, _p0 uintptr, flags int, mode uint32) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_openat)), 4, uintptr(dirfd), _p0, uintptr(flags), uintptr(mode), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpathconf(_p0 uintptr, name int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_pathconf)), 2, _p0, uintptr(name), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpause() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_pause)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpread(fd int, _p0 uintptr, _lenp0 int, offset int64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_pread)), 4, uintptr(fd), _p0, uintptr(_lenp0), uintptr(offset), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpwrite(fd int, _p0 uintptr, _lenp0 int, offset int64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_pwrite)), 4, uintptr(fd), _p0, uintptr(_lenp0), uintptr(offset), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callread(fd int, _p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_read)), 3, uintptr(fd), _p0, uintptr(_lenp0), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callreadlink(_p0 uintptr, _p1 uintptr, _lenp1 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_readlink)), 3, _p0, _p1, uintptr(_lenp1), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrename(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_rename)), 2, _p0, _p1, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrenameat(olddirfd int, _p0 uintptr, newdirfd int, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_renameat)), 4, uintptr(olddirfd), _p0, uintptr(newdirfd), _p1, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrmdir(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_rmdir)), 1, _p0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllseek(fd int, offset int64, whence int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_lseek)), 3, uintptr(fd), uintptr(offset), uintptr(whence), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callselect(nfd int, r uintptr, w uintptr, e uintptr, timeout uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_select)), 5, uintptr(nfd), r, w, e, timeout, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetegid(egid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setegid)), 1, uintptr(egid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callseteuid(euid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_seteuid)), 1, uintptr(euid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetgid(gid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setgid)), 1, uintptr(gid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsethostname(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_sethostname)), 2, _p0, uintptr(_lenp0), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetpgid(pid int, pgid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setpgid)), 2, uintptr(pid), uintptr(pgid), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetpriority(which int, who int, prio int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_setpriority)), 3, uintptr(which), uintptr(who), uintptr(prio), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetregid(rgid int, egid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setregid)), 2, uintptr(rgid), uintptr(egid), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetreuid(ruid int, euid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setreuid)), 2, uintptr(ruid), uintptr(euid), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetsid() (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setsid)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetuid(uid int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_setuid)), 1, uintptr(uid), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callshutdown(s int, how int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket_shutdown)), 2, uintptr(s), uintptr(how), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callstat(_p0 uintptr, stat uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_stat)), 2, _p0, stat, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callstatvfs(_p0 uintptr, vfsstat uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_statvfs)), 2, _p0, vfsstat, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsymlink(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_symlink)), 2, _p0, _p1, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsync() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_sync)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsysconf(which int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_sysconf)), 1, uintptr(which), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calltimes(tms uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_times)), 1, tms, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calltruncate(_p0 uintptr, length int64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_truncate)), 2, _p0, uintptr(length), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfsync(fd int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_fsync)), 1, uintptr(fd), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callftruncate(fd int, length int64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_ftruncate)), 2, uintptr(fd), uintptr(length), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callumask(mask int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_umask)), 1, uintptr(mask), 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calluname(buf uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libc_uname)), 1, buf, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callumount(_p0 uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_umount)), 2, _p0, uintptr(flags), 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callunlink(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_unlink)), 1, _p0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callunlinkat(dirfd int, _p0 uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_unlinkat)), 3, uintptr(dirfd), _p0, uintptr(flags), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callustat(dev int, ubuf uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_ustat)), 2, uintptr(dev), ubuf, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutime(_p0 uintptr, buf uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_utime)), 2, _p0, buf, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_bind(s int, addr uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_bind)), 3, uintptr(s), addr, addrlen, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_connect(s int, addr uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_connect)), 3, uintptr(s), addr, addrlen, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmmap(addr uintptr, length uintptr, prot int, flag int, fd int, pos int64) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_mmap)), 6, addr, length, uintptr(prot), uintptr(flag), uintptr(fd), uintptr(pos))
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunmap(addr uintptr, length uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_munmap)), 2, addr, length, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsendfile(outfd int, infd int, offset uintptr, count int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsendfile_sendfile)), 4, uintptr(outfd), uintptr(infd), offset, uintptr(count), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_sendto(s int, _p0 uintptr, _lenp0 int, flags int, to uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_sendto)), 6, uintptr(s), _p0, uintptr(_lenp0), uintptr(flags), to, addrlen)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_socket(domain int, typ int, proto int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_socket)), 3, uintptr(domain), uintptr(typ), uintptr(proto), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_socketpair(domain int, typ int, proto int, fd uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_socketpair)), 4, uintptr(domain), uintptr(typ), uintptr(proto), fd, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callwrite(fd int, _p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_write)), 3, uintptr(fd), _p0, uintptr(_lenp0), 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_getsockopt(s int, level int, name int, val uintptr, vallen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket___xnet_getsockopt)), 5, uintptr(s), uintptr(level), uintptr(name), val, vallen, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpeername(fd int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = rawSysvicall6(uintptr(unsafe.Pointer(&libsocket_getpeername)), 3, uintptr(fd), rsa, addrlen, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetsockopt(s int, level int, name int, val uintptr, vallen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket_setsockopt)), 5, uintptr(s), uintptr(level), uintptr(name), val, vallen, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrecvfrom(fd int, _p0 uintptr, _lenp0 int, flags int, from uintptr, fromlen uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libsocket_recvfrom)), 6, uintptr(fd), _p0, uintptr(_lenp0), uintptr(flags), from, fromlen)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callport_create() (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_port_create)), 0, 0, 0, 0, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callport_associate(port int, source int, object uintptr, events int, user uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_port_associate)), 5, uintptr(port), uintptr(source), object, uintptr(events), user, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callport_dissociate(port int, source int, object uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_port_dissociate)), 3, uintptr(port), uintptr(source), object, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callport_get(port int, pe uintptr, timeout uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_port_get)), 3, uintptr(port), pe, timeout, 0, 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callport_getn(port int, pe uintptr, max uint32, nget uintptr, timeout uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_port_getn)), 5, uintptr(port), pe, uintptr(max), nget, timeout, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callputmsg(fd int, clptr uintptr, dataptr uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_putmsg)), 4, uintptr(fd), clptr, dataptr, uintptr(flags), 0, 0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetmsg(fd int, clptr uintptr, dataptr uintptr, flags uintptr) (r1 uintptr, e1 Errno) {
	r1, _, e1 = sysvicall6(uintptr(unsafe.Pointer(&libc_getmsg)), 4, uintptr(fd), clptr, dataptr, flags, 0, 0)
	return
}

